version: '3'
services:
  pbx:
    build: backend
    volumes:
      - $PWD/backend/keys:/etc/asterisk/keys
      - $PWD/backend/etc/asterisk/http.conf:/etc/asterisk/http.conf
      - $PWD/backend/etc/asterisk/sip.conf:/etc/asterisk/sip.conf
      - $PWD/backend/etc/asterisk/extensions.conf:/etc/asterisk/extensions.conf
    # network_mode: "host"
    ports:
      - 8089:8089
      - 8088:8089
